CREATE TABLE public.STUDY_GOAL (
    ID_STUDY_GOAL serial4 NOT NULL,
    ID_TYPE_PERIOD serial4 NOT NULL,
    PERIOD_GOAL int4 NOT NULL,
    LINK_COURSE varchar(255) NULL,
    NOTE varchar(500) NULL,
    COMPLETE_STUDY int4 NULL DEFAULT 0,
    CONSTRAINT STUDY_GOAL_pkey PRIMARY KEY (ID_STUDY_GOAL),
    CONSTRAINT ID_TYPE_PERIOD_fkey FOREIGN KEY (ID_TYPE_PERIOD) REFERENCES public.TYPE_PERIOD(ID_TYPE_PERIOD)
);